name: deploy
on:
  push:
    tags:        
      - v*

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: run-tests
        run: docker-compose -f docker-compose-ci.yml up --exit-code-from test
      - name: pack
        run: ./utils/lambda.sh
      - name: deploy-core-prod
        run: ./utils/deploy.js
        env:
          FUNCTION_NAME: 'mestoCoreProd',
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
      - name: deploy-core-prod-locations
        run: ./utils/deploy.js
        env:
          FUNCTION_NAME: 'mestoCoreProdLocations',
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
